# Generated by Django 2.2.12 on 2020-07-10 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseModel',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default=None, max_length=30, unique=True)),
                ('faculty', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('fee', models.FloatField()),
                ('duration', models.IntegerField()),
            ],
        ),
    ]
