# Generated by Django 2.2.12 on 2020-07-12 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0002_studentmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrollModel',
            fields=[
                ('eid', models.AutoField(primary_key=True, serialize=False)),
                ('cid', models.IntegerField()),
                ('contact', models.IntegerField()),
            ],
        ),
    ]
